"""Enrich the API JSONL with a retrieval-friendly explanation per record,
generated by a local OpenAI-compatible LLM server.

To keep hallucination down, the model is only ever shown the record's own
fields (extracted from the installed package via introspection) and is told
that's the only information it may use - it never gets asked to recall or
look up anything about the library on its own.
"""

import json
import sys
import time
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "config"))
from config import LLM_BASE_URL, LLM_MODEL, LLM_VERIFY_SSL, api_jsonl_path, load_llm_api_key

if not LLM_VERIFY_SSL:
    requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.InsecureRequestWarning)

SYSTEM_PROMPT = (
    "You write short, retrieval-friendly explanations for a RAG database of "
    "a Python library's API. You will be given one API's metadata as JSON, "
    "extracted directly from the installed package via introspection - this "
    "is the ONLY information you may use. Do not add facts you recall about "
    "this library from your own training. If the given data is sparse, write "
    "a short, accurate sentence instead of guessing at missing details. "
    "Output 1-3 plain sentences, no markdown, no headers."
)
SAVE_EVERY = 20
MAX_RETRIES = 3


def read_jsonl(path):
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def write_jsonl(records, path):
    with open(path, "w", encoding="utf-8") as f:
        for record in records:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")


def build_context(record):
    context = {k: v for k, v in record.items() if k != "explanation"}
    return json.dumps(context, ensure_ascii=False, indent=2)


def call_llm(record, api_key):
    context = build_context(record)
    response = requests.post(
        f"{LLM_BASE_URL}/chat/completions",
        headers={"Authorization": f"Bearer {api_key}"},
        json={
            "model": LLM_MODEL,
            "temperature": 0.2,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"API metadata:\n{context}\n\nExplain `{record['name']}`."},
            ],
        },
        timeout=60,
        verify=LLM_VERIFY_SSL,
    )
    if not response.ok:
        raise requests.HTTPError(
            f"{response.status_code} {response.reason} for {response.url}: {response.text[:500]}",
            response=response,
        )
    return response.json()["choices"][0]["message"]["content"].strip()


def call_llm_with_retry(record, api_key):
    for attempt in range(MAX_RETRIES):
        try:
            return call_llm(record, api_key)
        except Exception as e:
            if attempt == MAX_RETRIES - 1:
                print(f"  FAILED {record['name']}: {e}")
                return None
            time.sleep(2 ** attempt)


def enrich_with_explanations(records, api_key, path):
    pending = [r for r in records if not r.get("explanation")]
    print(f"{len(records)} records, {len(pending)} need an explanation")

    for i, record in enumerate(pending):
        explanation = call_llm_with_retry(record, api_key)
        if explanation:
            record["explanation"] = explanation
            print(f"  [{i + 1}/{len(pending)}] {record['name']}")

        if (i + 1) % SAVE_EVERY == 0:
            write_jsonl(records, path)

    write_jsonl(records, path)


def main():
    import pycolmap

    path = api_jsonl_path(pycolmap.__version__)
    api_key = load_llm_api_key()

    records = read_jsonl(path)
    enrich_with_explanations(records, api_key, path)
    print(f"Done. Wrote explanations to {path}")


if __name__ == "__main__":
    main()
