"""Enrich each record JSONL with a retrieval-friendly explanation per
record, generated by a local OpenAI-compatible LLM server.

To keep hallucination down, the model is only ever shown the record's own
fields (extracted from the installed package via introspection, or read
from official example sources) and is told that's the only information it
may use - it never gets asked to recall or look up anything about the
library on its own.

API records and example records get different prompts: describing what an
introspected API is and describing what a code snippet accomplishes are
different jobs, and one prompt covering both did neither well.
"""

import json
import sys
import time
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "config"))
from config import (
    API_KEY,
    LLM_BASE_URL,
    LLM_MODEL,
    VERIFY_SSL,
    parsed_module_name,
    record_jsonl_paths,
)

if VERIFY_SSL is False:
    requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.InsecureRequestWarning)

GROUNDING_RULE = (
    "What you are given is the ONLY information you may use. Do not add "
    "facts you recall about this library from your own training. If the "
    "given data is sparse, write a short, accurate sentence instead of "
    "guessing at missing details. Output 1-3 plain sentences, no markdown, "
    "no headers."
)

API_SYSTEM_PROMPT = (
    "You write short, retrieval-friendly explanations for a RAG database of "
    "a Python library's API. You will be given one API's metadata, "
    "extracted directly from the installed package via introspection. "
    + GROUNDING_RULE
)

EXAMPLE_SYSTEM_PROMPT = (
    "You write short, retrieval-friendly explanations for a RAG database of "
    "official example code for a Python library. You will be given one "
    "snippet - a function, a class, or a file's module-level scaffolding - "
    "along with the library APIs it references. Write what a developer "
    "searching for this would want to match on: the task the code "
    "accomplishes and how it uses those APIs, not a line-by-line "
    "paraphrase. "
    "Base your explanation on the executable code, not on its docstring or "
    "comments. Those may be out of date or describe the wider file rather "
    "than this snippet, so treat them as supporting hints only: you may "
    "draw on them, but every explanation must account for what the code "
    "itself actually does. "
    "Describe only what is actually in the snippet you are shown - if it "
    "is just imports and an entry point, say that it is the file's setup "
    "and note what the file as a whole works with, rather than describing "
    "work the snippet does not contain. "
    + GROUNDING_RULE
)

SAVE_EVERY = 20
MAX_RETRIES = 3


def read_jsonl(path):
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def write_jsonl(records, path):
    with open(path, "w", encoding="utf-8") as f:
        for record in records:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")


def build_prompt(record):
    """(system prompt, user message) for this record's kind. Example code
    is handed over as a raw block rather than inside the JSON, where
    json.dumps would escape every newline into \\n and leave the model
    reading source as one long line."""
    if record.get("kind") == "example":
        metadata = {k: v for k, v in record.items() if k not in ("explanation", "code")}
        user = (
            f"Example metadata:\n{json.dumps(metadata, ensure_ascii=False, indent=2)}\n\n"
            f"Code:\n{record.get('code', '')}\n\n"
            f"Explain this snippet."
        )
        return EXAMPLE_SYSTEM_PROMPT, user

    context = {k: v for k, v in record.items() if k != "explanation"}
    user = (
        f"API metadata:\n{json.dumps(context, ensure_ascii=False, indent=2)}\n\n"
        f"Explain `{record['name']}`."
    )
    return API_SYSTEM_PROMPT, user


def call_llm(record, api_key):
    system_prompt, user_message = build_prompt(record)
    response = requests.post(
        f"{LLM_BASE_URL}/chat/completions",
        headers={"Authorization": f"Bearer {api_key}"},
        json={
            "model": LLM_MODEL,
            "temperature": 0.2,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message},
            ],
        },
        timeout=60,
        verify=VERIFY_SSL,
    )
    if not response.ok:
        raise requests.HTTPError(
            f"{response.status_code} {response.reason} for {response.url}: {response.text[:500]}",
            response=response,
        )
    return response.json()["choices"][0]["message"]["content"].strip()


def call_llm_with_retry(record, api_key):
    for attempt in range(MAX_RETRIES):
        try:
            return call_llm(record, api_key)
        except Exception as e:
            if attempt == MAX_RETRIES - 1:
                print(f"  FAILED {record['name']}: {e}")
                return None
            time.sleep(2 ** attempt)


def enrich_with_explanations(records, api_key, path):
    pending = [r for r in records if not r.get("explanation")]
    print(f"{len(records)} records, {len(pending)} need an explanation")

    for i, record in enumerate(pending):
        explanation = call_llm_with_retry(record, api_key)
        if explanation:
            record["explanation"] = explanation
            print(f"  [{i + 1}/{len(pending)}] {record['name']}")

        if (i + 1) % SAVE_EVERY == 0:
            write_jsonl(records, path)

    write_jsonl(records, path)


def main():
    for path in record_jsonl_paths(__import__(parsed_module_name).__version__):
        if not path.exists():
            print(f"Skipping {path} (not generated yet)")
            continue
        records = read_jsonl(path)
        enrich_with_explanations(records, API_KEY, path)
        print(f"Done. Wrote explanations to {path}")


if __name__ == "__main__":
    main()
